### ISSUE TITLE
Improve Visualisation

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/wai-sdg-portal#100]
- [x] Add title on the top of the chart, the subtitle should have an administration and filters if user filter the data
- [x] Also add stack as subtitle (if the feature flag is active)
- [x] Add xAxis (question) and yAxis (option, left vertical) labels

**Comment by wayangalihpratama** [comment]
- [ ] Update main chart text title to a sentences

**Comment by wayangalihpratama** [comment]
- [ ] xAxis: centered, labeled by question selected
- [ ] yAxis: change label from option to count
