### ISSUE TITLE
History chart visualisation

### ISSUE THREAD

**Issue by wayangalihpratama** [akvo/wai-sdg-portal#101]
- [x] Add a chart button beside history button on table expand
- [x] Setup global store to save historyChart dataPointId, questionId, and questionType
- [x] Get history data and show the chart on Main dashboard page

**Comment by wayangalihpratama** [comment]
- [ ] History chart date not really order by datetime updated

**Comment by wayangalihpratama** [comment]
- [ ] Show all option value for yAxis

**Comment by dedenbangkit** [comment]
History Chart is still not properly ordered for number type of question
