### ISSUE TITLE
Manage form passcode tab

### ISSUE THREAD

**Issue by joycarpediem** [akvo/wai-sdg-portal#226]
FE : @navins94 
* Add new tab in admin screen 
* The page shows a table . Columns are form name  , URL , passcode field 
* The passcode column will contain text box and edit and save buttons . The text field is encrypted by default . On clicking edit it shows the current value and the text field becomes editable . User can then change and save or just save
* On clicking edit we should throw a warning popup . The popup should say : "All current data collection will be effected if you change the form passcode . All data collectors will need to be informed about the new passcode . Do you still want to edit the passcode"
* The url field should have copy functionality 
* Check if we can implement URL shortener

BE : @wayangalihpratama 
* Implement logic to generate form url ( check logic in webform.akvo.org)
* Expose in the form list API

Passcode API @navins94 
* Add column in form table for passcode
* Create an API to fetch passcode
* Create API to manage passcode

**Comment by wayangalihpratama** [comment]
- Need to finish and merge #224 and #225 before starting to create Passcode API (blocked by migration).

**Comment by navins94** [comment]
Update table UI @navins94

**Comment by joycarpediem** [comment]
- [ ] Add provision to view the passcode in read only mode without having to edit it
- [ ] reduce constraints on passcode . Just a length check of  >= 4 should be enough

@navins94

**Comment by navins94** [comment]
@joycarpediem Sure I will make that change

**Comment by joycarpediem** [comment]
👍🏽
