### ISSUE TITLE
JMP service level computation -- Generic iteration

### ISSUE THREAD

**Issue by joycarpediem** [akvo/wai-sdg-portal#231]

**Comment by dedenbangkit** [comment]
https://pypi.org/project/AkvoResponseGrouper/

**Comment by dedenbangkit** [comment]
| INFO | LINK |
| ------------- | ------------- |
| **Package** | https://pypi.org/project/AkvoResponseGrouper/ |
| **Repo**       | https://github.com/akvo/Akvo-ResponseGrouper |
| **Schema**  | https://github.com/akvo/Akvo-ResponseGrouper/blob/main/docs/database.org#views |

## Preview

![Firefox_Screenshot_2023-01-12T10-05-05 740Z](https://user-images.githubusercontent.com/3245109/212037960-e1c544d8-b0d0-4bb3-8060-931a7d6c71f5.png)
