### ISSUE TITLE
Local Deploy or Non GCP

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/wai-sdg-portal#269]
## Add New Docker Compose to:

- Build Documentation + Frontend
- Serve Frontend to NGINX
- Build Backend, use as Backend & Worker:
  - Backend: run.sh
  - Worker: run-worker.sh

---------------------

## Update Readme

**Comment by joycarpediem** [comment]
@dedenbangkit , has this been tested ? Can this be closed ?
