### ISSUE TITLE
Dev Database Issue

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/wai-sdg-portal#317]
Currently, database name in the dev environment is using "_" as separator.

Since the connection for Response Grouper access is using the actual database URL, we need to make it easier for developer to debug.

# Solution
- Replace all the init db with instance name

**Comment by joycarpediem** [comment]
@dedenbangkit , can this be moved to ready for testing . Also how will we test this ?

**Comment by dedenbangkit** [comment]
Yeah, this is done @joycarpediem.  I have merged this to Sandbox branch. Only need to inform the dev team about the changes.
